networks:
  tor-egress:
    driver: bridge
  onion-tier:
    internal: true

services:
  red_dark_node:
    build: .
    container_name: red_dark_node
    restart: unless-stopped
    networks:
      - onion-tier
    environment:
      - RED_NODE_NAME=Onion-Vault-Secure
      - RED_PORT=9090
      - RED_DATA_DIR=/app/data/restricted
    volumes:
      - ./data/restricted:/app/data/restricted:ro

  tor_sidecar:
    image: goldy/tor-hidden-service:latest
    container_name: tor_sidecar
    restart: unless-stopped
    networks:
      - tor-egress
      - onion-tier
    links:
      - red_dark_node
    environment:
      # This dictates the folder name inside /var/lib/tor
      VAULT_TOR_SERVICE_HOSTS: "80:red_dark_node:9090"
    volumes:
      # Switched to a Named Volume to fix the permission crash loop
      - tor_data:/var/lib/tor
    depends_on:
      - red_dark_node

volumes:
  tor_data:
